### ISSUE TITLE
McAfee License?

### ISSUE THREAD

**Issue by sparrell** [opencybersecurityalliance/opendxl-ontology#6]
I notice the license (https://github.com/opencybersecurityalliance/opendxl-ontology/blob/master/LICENSE) is copyright to McAfee “all rights reserved”. Does this imply all contributions to this will be copyright McAfee? Should this be copyright OASIS?

**Comment by JasonKeirstead** [comment]
I am not a lawyer disclaimer, etc...

Technically, the copyright is owned by whomever wrote it, so since McAfee donated the code, they have the initial copyright. 

Also technically, the License file *should* be updated with all of the other copyright holders, every time a PR is merged into the codebase (ie Copyright A, B, C). But I have never seen anyone do that in any open source project!

None of this any real practical ramifications, since the code is Apache licensed.

**Comment by JasonKeirstead** [comment]
I will forward this onto Jamie to make sure I am not speaking incorrectly.

**Comment by JasonKeirstead** [comment]
Actually - you may be right as the OASIS OP template license has a different blurb on it, this is what we used in STIX Shifter.

https://github.com/opencybersecurityalliance/stix-shifter/blob/master/LICENSE.md

**Comment by chrissmith-mcafee** [comment]
Agreed, that is the incorrect license file. I will update it to be consistent with the license in STIX Shifter.

**Comment by jamienewlaw** [comment]
Chris, at the risk of writing about legal stuff in a repo :)  the new form of LICENSE.md to which Jason pointed should go into the contributed version's file ... because that's what tells devs and others that the current FOSS terms apply (and may have brief related relevant OASIS notices).  I see you did that, thanks.  However, if you want to leave your notice in there, you also may do so, so long as it doesn't vitiate the main LICENSE.md.  Some companies ask to retain their own notice for compliance reasons, and you should feel free to contact me (or have your licensing suits do so) if they wish to do that and want to chat about it.  Likely we'd suggest something like LICENSE-PRIOR.md    Regards, Jamie from OASIS

**Comment by sparrell** [comment]
License was updated.
